apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gogs-ingress
spec:
  rules:
    - host: demo.gogs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gogs
            port:
              number: 3000
